config/routes.rb
Rails.application.routes.draw do
  root 'currency_exchange_pairs#index'
  resources :currency_exchange_pairs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency_exchange_pair.rb
class CurrencyExchangePair < ApplicationRecord
  validates :number_of_weeks, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 52,
                                                              greater_than: 0 }
  validates :amount, presence: true
  validates_inclusion_of :base_currency, in: Constants::SUPPORTED_CURRENCIES,
                                         allow_nil: false, message: 'Currency is not valid'

  validates_inclusion_of :target_currency, in: Constants::SUPPORTED_CURRENCIES,
                                           allow_nil: false, message: 'Currency is not valid'
end

app/models/currency_exchange_rate.rb
# frozen_string_literal: true

class CurrencyExchangeRate < ApplicationRecord
  validates :rate, presence: true
  validates :date, presence: true

  validates_inclusion_of :base_currency, in: Constants::SUPPORTED_CURRENCIES,
                                         allow_nil: false

  validates_inclusion_of :target_currency, in: Constants::SUPPORTED_CURRENCIES,
                                           allow_nil: false

  scope :between_dates, ->(date_range) { where(date: date_range) }
  scope :by_target_currency, ->(currency) { where(target_currency: currency) }

  def self.exists_for_date?(date)
    CurrencyExchangeRate.find_by(date: date).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currency_exchange_pairs_controller.rb
class CurrencyExchangePairsController < ApplicationController
  before_action :set_currency_exchange_pair, only: %i[show edit update destroy]

  # GET /currency_exchange_pairs
  def index
    @currency_exchange_pairs = CurrencyExchangePair.all
  end

  # GET /currency_exchange_pairs/1
  # GET /currency_exchange_pairs/1.json

  def show
    @current_exchange = @currency_exchange_pair.decorate
  end

  # GET /currency_exchange_pairs/new
  def new
    @currency_exchange_pair = CurrencyExchangePair.new
  end

  # GET /currency_exchange_pairs/1/edit
  def edit; end

  # POST /currency_exchange_pairs
  def create
    @currency_exchange_pair = CurrencyExchangePair.new(currency_exchange_pair_params)

    respond_to do |format|
      if @currency_exchange_pair.save
        format.html { redirect_to @currency_exchange_pair, notice: 'Currency exchange pair was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /currency_exchange_pairs/1
  def update
    respond_to do |format|
      if @currency_exchange_pair.update(currency_exchange_pair_params)
        format.html { redirect_to @currency_exchange_pair, notice: 'Currency exchange pair was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /currency_exchange_pairs/1
  def destroy
    @currency_exchange_pair.destroy
    respond_to do |format|
      format.html do
        redirect_to currency_exchange_pairs_url, notice: 'Currency exchange pair was successfully destroyed.'
      end
    end
  end

  private

  def set_currency_exchange_pair
    @currency_exchange_pair = CurrencyExchangePair.find(params[:id])
  end

  # white list exchange pair params .
  def currency_exchange_pair_params
    params.require(:currency_exchange_pair).permit(:base_currency, :target_currency, :number_of_weeks, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_exchange_pairs_helper.rb
module CurrencyExchangePairsHelper
end

app/views/currency_exchange_pairs/_form.html.erb
<%= form_for @currency_exchange_pair, :html => { :class => "form-horizontal currency_exchange_pair" } do |f| %>


  <div class="form-group">
    <%= f.label :base_currency, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :base_currency, :class => 'form-control', :required => true %>
      <%=f.error_span(:base_currency) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :target_currency, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :target_currency, :class => 'form-control', :required => true %>
      <%=f.error_span(:target_currency) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :amount, :class => 'form-control ', :required => true %>
      <%=f.error_span(:amount) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :number_of_weeks, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :number_of_weeks, :class => 'form-control', :required => true %>
      <%=f.error_span(:number_of_weeks) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                currency_exchange_pairs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/currency_exchange_pairs/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Base currency</th>
      <th>Target currency</th>
      <th>Date</th>
      <th>Exchange rate</th>
      <th>Valuation</th>
      <th> P/L </th>
    </tr>
  </thead>
  <tbody>
    <% @current_exchange.historic_data.each do |exchange_rate| %>
        <tr class="exchange-rate-<%= exchange_rate[1] %>">
          <td> <%= @currency_exchange_pair.base_currency %> </td>
          <td> <%= @currency_exchange_pair.target_currency %> </td>
          <td> <%= exchange_rate[0] %> </td>
          <td> <%= exchange_rate[1] %> </td>
          <% # TBD: move to decorator  %>
          <td> <%= @currency_exchange_pair.amount * (exchange_rate[1] || 0) %> </td>
          <td> <%= @currency_exchange_pair.amount * ((exchange_rate[1] ||0) - @current_exchange.current_rate) %> </td>
        </tr>
      <%end%>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function(){
    var weekpicker = $("#weekpicker1").weekpicker({ minDate: "<%= @current_exchange.minmax_date[0] %>", maxDate: "<%= Date.today %>"});

    highlightDataTable(weekpicker);
  });
</script>

app/views/currency_exchange_pairs/edit.html.erb
<%- model_class = CurrencyExchangePair -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/currency_exchange_pairs/index.html.erb
<%- model_class = CurrencyExchangePair -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:base_currency) %></th>
      <th><%= model_class.human_attribute_name(:target_currency) %></th>
      <th><%= model_class.human_attribute_name(:number_of_weeks) %></th>
      <th><%= model_class.human_attribute_name(:amount_in_base_currency) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @currency_exchange_pairs.each do |currency_exchange_pair| %>
      <tr>
        <td><%= link_to currency_exchange_pair.id, currency_exchange_pair_path(currency_exchange_pair) %></td>
        <td><%= currency_exchange_pair.base_currency %></td>
        <td><%= currency_exchange_pair.target_currency %></td>
        <td><%= currency_exchange_pair.number_of_weeks %></td>
        <td><%= currency_exchange_pair.amount %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      currency_exchange_pair_path(currency_exchange_pair), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_currency_exchange_pair_path(currency_exchange_pair), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      currency_exchange_pair_path(currency_exchange_pair),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_currency_exchange_pair_path,
            :class => 'btn btn-primary' %>

app/views/currency_exchange_pairs/new.html.erb
<%- model_class = CurrencyExchangePair -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/currency_exchange_pairs/show.html.erb
<%- model_class = CurrencyExchangePair -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="col-md-6">
      <div class="pull-left">
        <dl class="dl-horizontal">
          <dt><strong><%= model_class.human_attribute_name(:base_currency) %>:</strong></dt>
          <dd><%= @currency_exchange_pair.base_currency %></dd>
          <dt><strong><%= model_class.human_attribute_name(:target_currency) %>:</strong></dt>
          <dd><%= @currency_exchange_pair.target_currency %></dd>
          <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
          <dd><%= @currency_exchange_pair.amount %></dd>
          <dt><strong><%= model_class.human_attribute_name(:number_of_weeks) %>:</strong></dt>
          <dd><%= @currency_exchange_pair.number_of_weeks %></dd>
          <dt><strong>Current Rate:</strong></dt>
          <dd><%= @current_exchange.current_rate %></dd>
          <dt><strong class="max-rate">Highest Value:</strong></dt>
          <dd><%= @current_exchange.minmax_rate[1] %></dd>
          <dt><strong class="min-rate">Lowest Value:</strong></dt>
          <dd><%= @current_exchange.minmax_rate[0] %></dd>
        </dl>
        <dl class="dl-horizontal">
          <dt><strong>Select Week:</strong></dt>
          <dd>
            <div class="input-group align-items-center">
              <div id="weekpicker1"></div>
            </div>
          </dd>
        </dl>
      </div>
    </div>
    <div class="col-md-6">
      <div class="pull-right">
        <%= link_to t('.back', :default => t("helpers.links.back")),
                  currency_exchange_pairs_path, :class => 'btn btn-default'  %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_currency_exchange_pair_path(@currency_exchange_pair), :class => 'btn btn-default' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      currency_exchange_pair_path(@currency_exchange_pair),
                      :method => 'delete',
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

<%= render :partial => 'table' %>

<%= line_chart @current_exchange.historic_data, xtitle: "Duration (#{@currency_exchange_pair.number_of_weeks} weeks)", ytitle: "Price", min: @current_exchange.minmax_rate[0], max: @current_exchange.minmax_rate[1] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExchangeRate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>